# Forzar reconstrucción y desactivar caché
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP_CACHE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
